#server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/minesweeper?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=minesweeper_admin
spring.datasource.password=${MINESWEEPER_ADMIN_DB_PASS:admin_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Логин для входа в админку (пока простой, в шаге 6 заменим на БД)
admin.username=admin
admin.password-hash=${MINESWEEPER_ADMIN_HASH:$2a$10$14J0fUAXAWQiLkSg7QQ.EuVBF2CkU5O8cyEX4zc4ihUDi22uuP6Ca}

# Thymeleaf
spring.thymeleaf.cache=false

server.port=8443
server.ssl.key-store=file:D:/game/admin-keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-alias=admin
